name: Project Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        env:
          key: ${{secrets.API_KEYS }}

        run: |
          python -m pip install --upgrade pip
          pip install -U pytest
          pip install requests
          pip install python-dotenv
      - name: Test with pytest
        run: pytest -vv

  # secrets-in-github-actions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: step 1 -Echo out a github action secrete key.
  #       env:
  #         key: ${{secrets.API_KEYS }}
  #       run: |
  #         echo ${{env.key}}
